### PR TITLE
Fix generating docs for UnixXXXStream

### PR DESCRIPTION
**Pull request by EPashkin**
#208 broke apveyor doc test
https://ci.appveyor.com/project/GuillaumeGomez/gtk/builds/24553406/job/nq5dssq5o0dhxnj6#L209
```
 --> C:\Users\appveyor\.cargo\git\checkouts\gio-a4b825b310a073b9\10df4f6\src\unix_input_stream.rs:10:14
   |
10 | use std::os::unix::io::{RawFd, AsRawFd, IntoRawFd, FromRawFd};
   |              ^^^^ could not find `unix` in `os`
```

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
It's up to @sdroege now. :)

**Comment by sdroege** [comment]
Thanks!

**Pull request merged**
