### PR TITLE
Fix doc build

### PR DESCRIPTION
**Pull request by EPashkin**
Fix doc builds found in https://github.com/gtk-rs/gtk/pull/622

cc @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Great, thanks!

**Comment by EPashkin** [comment]
Seems comments this need be moved to lgpl-docs.
Any comment about text or format?

**Comment by GuillaumeGomez** [comment]
Not really. Should I?

**Comment by EPashkin** [comment]
Strange: docs generated, but no docs for `IntoRawFd` or no link from  `new_from_fd` for me (windows).
Also link for windows specific `IntoRawSocket` [wrong](https://doc.rust-lang.org/nightly/std/sys/windows/ext/io/trait.IntoRawSocket.html) (maybe because I build under nightly).
Finally no `This is supported on Windows only.` on `new_from_socket` like on https://doc.rust-lang.org/std/os/windows/io/trait.IntoRawSocket.html :sob:

So doc comments only stays in source file.

**Comment by GuillaumeGomez** [comment]
Yes, world is a bitch. :'(

**Comment by EPashkin** [comment]
Anyway CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
