### PR TITLE
Fix build docs for non unix (second attempt)

### PR DESCRIPTION
**Pull request by EPashkin**
Fix error found on building docs in gtk-rs/gdk#194

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Aaaaaaah! Now I see! But isn't it strange that windows build is just working fine already?

**Comment by EPashkin** [comment]
unix_socket_address.rs included only on unix or dox

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Let's check on gdk now! :)

**Pull request merged**
