### PR TITLE
Regenerate autogenerated bindings with latest GIR

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
This PR also also update gir submodule to matched version.
Other that this I almost sure that it good as only generated files changed, will confirm at evening.

**Comment by EPashkin** [comment]
Thanks @sdroege all good.
IMHO better postpone merge until https://github.com/gtk-rs/gtk/pull/509 merged

**Comment by EPashkin** [comment]
@GuillaumeGomez please restart CI here

**Comment by GuillaumeGomez** [comment]
Yes sir!

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, seems this PR ready for merge.

@sdroege Thanks again

**Comment by sdroege** [comment]
So only this one is missing then, then I can go back to the next gir changes :)

**Comment by EPashkin** [comment]
Ping

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
