### PR TITLE
More Tls bindings: missing files

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
These went missing from https://github.com/gtk-rs/gio/pull/83

### CODE REVIEW

**Comment by EPashkin** [comment]
@MathieuDuponchelle Please, update `gir-files` submodule: it was mistakenly reverted back in #86.
Generated file must have `https://github.com/gtk-rs/gir-files @ 77d1f70` in header.

**Comment by MathieuDuponchelle** [comment]
I'm a bit confused, is the new commit what you expect ?

**Comment by EPashkin** [comment]
Thanks, you done it as I think.
Lately I began to think that separate commits for submodule update is not necessary if main changes contains in single commit.

**Comment by MathieuDuponchelle** [comment]
> Lately I began to think that separate commits for submodule update is not necessary if main changes contains in single commit.

Would really be nice if update didn't change file headers IMO

**Comment by EPashkin** [comment]
@GuillaumeGomez I propose to merge this, we have my commit to check rustdoc fix

**Comment by EPashkin** [comment]
About version, maybe we need change versioning to adding single file with it? But this way we be not sure with which version file generated actually, specially in PR's
So currently I prefer current versioning.
@GuillaumeGomez, @sdroege Maybe you have better idea?

**Comment by GuillaumeGomez** [comment]
I must admit that I don't have an opinion in here. Otherwise, the PR seems good to me as well so I'll wait for the debate to end before merging it. ;)

**Comment by MathieuDuponchelle** [comment]
> I must admit that I don't have an opinion in here. Otherwise, the PR seems good to me as well so I'll wait for the debate to end before merging it. ;)

You shouldn't wait :) This shouldn't be blocked by a debate, by the way can i find you folks on an IRC channel? I'm on gtk-rs in on mozilla's servers, and rust on gimpnet, but if you're also there I don't recognize user names :)

**Comment by GuillaumeGomez** [comment]
I'm imperio there (on both IRC channels). And since you seem to be french, I'm also on `#rust-fr` (on mozilla server).

So since @EPashkin gave the go, I'll merge. Thanks!

**Comment by MathieuDuponchelle** [comment]
> I'm imperio there

That was not my first guess :)

**Comment by GuillaumeGomez** [comment]
I would assume so. Someone took the pseudo on github so I went for this one. :')

**Pull request merged**
