### PR TITLE
Generate Seekable

### PR DESCRIPTION
**Pull request by EPashkin**
cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sdroege** [comment]
Looks good to me. How did we forget that when doing all the streams? :)

**Comment by EPashkin** [comment]
It was need glib.SeekType, it don't generated at that time

**Comment by EPashkin** [comment]
@GuillaumeGomez CI ended with same rustdoc error on nightly

**Comment by GuillaumeGomez** [comment]
Yep, for now the rustdoc fix hasn't been merged so I'll just merge this one.

**Pull request merged**
