### PR TITLE
Regen and prelude fixes

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
CC @GuillaumeGomez @EPashkin

**Comment by EPashkin** [comment]
Seems examples need fix first

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍 after CI

**Comment by GuillaumeGomez** [comment]
About the failure: shouldn't we reexport all manual traits?

**Comment by GuillaumeGomez** [comment]
It makes no sense to me to be able to have `gio::Trait` but not `gio::TraitManual`...

**Comment by sdroege** [comment]
> It makes no sense to me to be able to have `gio::Trait` but not `gio::TraitManual`...

Yes. We don't do that? I'll check tomorrow, I might be confused :)

**Comment by sdroege** [comment]
Oh I see. Yes the way how the prelude was re-exported was actually good and we should keep that. Sorry for the confusion :)

So only the regeneration here now. Will merge once green

**Pull request merged**
