### PR TITLE
OsString support and regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/592

cc @GuillaumeGomez, @sdroege, @tmiasko

### CODE REVIEW

**Comment by tmiasko** [comment]
Upstream annotations seem to be incorrect for g_unix_is_system_device_path and
g_unix_is_system_fs_type. Those probably should accept path / filename
arguments.

Everything else looks great, thanks!

**Comment by EPashkin** [comment]
@tmiasko By test from gio source, seems it just string.
```
static void
test_is_system_fs_type (void)
{
  g_assert_true (g_unix_is_system_fs_type ("tmpfs"));
  g_assert_false (g_unix_is_system_fs_type ("ext4"));
}

```

**Comment by EPashkin** [comment]
Updated

**Comment by EPashkin** [comment]
I restarted Apveyor.
@GuillaumeGomez Please, restart travis too.

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by EPashkin** [comment]
Again all passed except single Travis build (due nightly futures)

**Comment by GuillaumeGomez** [comment]
Then it's good enough for me. Thanks @EPashkin! :)

**Comment by EPashkin** [comment]
@GuillaumeGomez Seems this PR ready for merge, I even forget about it.

**Comment by GuillaumeGomez** [comment]
Weird I forgot it as well... Sorry about that...

**Pull request merged**
