### PR TITLE
Gstring support

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by EPashkin** [comment]
This will also have problems:
```
  --> D:/eap/rust/0/gio\src\file.rs:62:20
   |
62 |         let etag = etag.into();
   |                    ^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the method body at 58:5...
  --> D:/eap/rust/0/gio\src\file.rs:58:5
   |
58 |     fn replace_contents_async_future<'a, B: AsRef<[u8]> + Send + 'static, P: Into<Option<&'a str>>>(&self, contents: B, etag: P, make_backup: bool, flags: FileCreateFlags) -> Box<futures_core::Future<Item = (Self, (B, glib::GString)), Error = (Self, (B, Error))>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...so that the expression is assignable:
           expected std::option::Option<&str>
              found std::option::Option<&'a str>
   = note: but, the lifetime must be valid for the static lifetime...
   = note: ...so that the types are compatible:
           expected std::convert::From<&str>
              found std::convert::From<&'static str>

```

**Comment by philn** [comment]
Hum, the build works here with 1.31. How can I reproduce this error?

**Comment by EPashkin** [comment]
I build examples with default uncommented.
Also possible build only gio with feature "futures"

**Comment by philn** [comment]
Ah right, I didn't notice the compile guard. Will try to fix it.

**Comment by EPashkin** [comment]
@GuillaumeGomez Strange, but I now can rerun\abort travis.

**Comment by EPashkin** [comment]
And CI passed now

**Comment by GuillaumeGomez** [comment]
> @GuillaumeGomez Strange, but I now can rerun\abort travis.

Well, that's a great thing!

Thanks @philn!

**Pull request merged**
