### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
```
error[E0599]: no method named `cancel` found for type `auto::cancellable::Cancellable` in the current scope
  --> D:/eap/rust/0/gio\src\gio_future.rs:89:25
   |
89 |               cancellable.cancel();
   |                           ^^^^^^
   | 
  ::: D:/eap/rust/0/gio\src\auto\cancellable.rs:19:1
   |
19 | / glib_wrapper! {
20 | |     pub struct Cancellable(Object<ffi::GCancellable, ffi::GCancellableClass, CancellableClass>);
21 | |
22 | |     match fn {
23 | |         get_type => || ffi::g_cancellable_get_type(),
24 | |     }
25 | | }
   | |_- method `cancel` not found for this
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use auto::cancellable::CancellableExt;`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by sdroege** [comment]
The third commit fixes that, or not?

**Comment by EPashkin** [comment]
Sorry, It was old error, all ok now in gio

**Comment by EPashkin** [comment]
Seems `g_subprocess_send_signal` UNIX only, "io\src\auto/subprocess.rs:214: undefined reference to `g_subprocess_send_signal'"
As https://developer.gnome.org/gio/2.56/GSubprocess.html#g-subprocess-send-signal says
"This API is not available on Windows."

**Comment by EPashkin** [comment]
Errors on apveyor also legit but IMHO need gir update.

**Comment by sdroege** [comment]
> Errors on apveyor also legit but IMHO need gir update.

Yeah those are an old bug in gir, fixing

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gir/pull/695

**Comment by sdroege** [comment]
This should also be fine now with the new gir

**Comment by EPashkin** [comment]
@sdroege Thansk, 👍

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
