### PR TITLE
Use single_version_file option

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/556
Apply https://github.com/gtk-rs/gir/pull/561

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Aren't a lot of files missing in here? All files into the `auto` folder should have their headers updated, no?

**Comment by EPashkin** [comment]
All changes is same, I do full regen after gir merged.
Currently working on travis checks

**Comment by EPashkin** [comment]
Updated travis to check regen only on first build

**Comment by EPashkin** [comment]
Updated with final regen

**Comment by EPashkin** [comment]
Added delay before invoking in async tests

**Comment by GuillaumeGomez** [comment]
Next reviews will be so much easier. :D

**Comment by EPashkin** [comment]
Strange, delay not works, I remove it then.

**Comment by EPashkin** [comment]
@GuillaumeGomez, can you restart travis? Or we can merge at current state?

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by EPashkin** [comment]
@GuillaumeGomez CI happy

**Pull request merged**
