### PR TITLE
Tls certificate

### PR DESCRIPTION
**Pull request by antoyo**
This is based on pull request #39.
Please merge it before.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by EPashkin** [comment]
@antoyo. please update regen this with latest gir

**Comment by antoyo** [comment]
@EPashkin: Done.

**Comment by EPashkin** [comment]
👍 Thanks

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
