### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/lgpl-docs/pull/48
Replaces https://github.com/gtk-rs/gio/pull/185

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
@sdroege You can merge now you know. :p

**Comment by sdroege** [comment]
It's still marked as WIP

**Comment by EPashkin** [comment]
Updated

**Comment by sdroege** [comment]
Can you restart CI now that the GLib PR is merged?

**Comment by sdroege** [comment]
All good for me otherwise

**Comment by EPashkin** [comment]
Restarted

**Comment by sdroege** [comment]
Sorry for the delay, back from FOSDEM now :)

**Pull request merged**
