### PR TITLE
Generate interface functions

### PR DESCRIPTION
**Pull request by EPashkin**
Apply gtk-rs/gir#349

### CODE REVIEW

**Comment by EPashkin** [comment]
Strange Travis stable errors repeated
```
error: couldn't read "src/bin/notebook.rs": No such file or directory (os error 2)
error: couldn't read "src/bin/builder_basics.rs": No such file or directory (os error 2)
``

**Comment by EPashkin** [comment]
Oh. it was not stable, but nightly :)

**Comment by GuillaumeGomez** [comment]
Nightly is a bit broken for the moment. :)

**Comment by EPashkin** [comment]
Seems it changed some time ago: http://doc.crates.io/guide.html#project-layout
Even 1.13.0 compile examples if I move *.rs to bin subfolder and remove [[bin]]s from Cargo.toml
So not sure that it really error.

**Comment by EPashkin** [comment]
@GuillaumeGomez Please restart travis

**Comment by GuillaumeGomez** [comment]
Nightly is broken as far as I know so it won't change if we restart.

**Comment by EPashkin** [comment]
Nightly cargo just changed rules without warnings  ;)
But now it passed.

**Comment by EPashkin** [comment]
Now it ready do merge

**Comment by GuillaumeGomez** [comment]
Oh nice! Thanks!

**Pull request merged**
