### PR TITLE
Enable InetAddress{Mask}::equal() and to_string()

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Can you update with latest gir. Or prefer it be in different PR?

**Comment by sdroege** [comment]
> @sdroege Can you update with latest gir. Or prefer it be in different PR?

@GuillaumeGomez is doing a PR for that already.

**Comment by EPashkin** [comment]
then 👍 Thanks

**Comment by EPashkin** [comment]
And other PR better based on this, or rebased after merge

**Comment by sdroege** [comment]
> And other PR better based on this, or rebased after merge

Shouldn't make any difference. The regen PR is not touching any of this, they can be handled independently.

**Comment by EPashkin** [comment]
Not sure about this

**Comment by sdroege** [comment]
I tested it :)

**Comment by sdroege** [comment]
Context where this was noticed is this btw: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/merge_requests/222#note_111642

**Comment by GuillaumeGomez** [comment]
All good to me as well, thanks!

**Comment by sdroege** [comment]
All good apart from the 1.28 builds, merging. (@GuillaumeGomez were you not planning to remove the 1.28 builds?)

**Pull request merged**
