### PR TITLE
Fix type errors on armv7l for desktop_app_info.rs and unix_socket_add…

### PR DESCRIPTION
**Pull request by meldron**
This PR fixes compile errors on armv7l (raspberry pi), see issue #137.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
If you could add a check for this on `travis`, it'd be awesome!

**Comment by sdroege** [comment]
Ugh, I just sent a PR for the same here https://github.com/gtk-rs/gio/pull/139 :)

**Comment by GuillaumeGomez** [comment]
I was about to comment about it. XD

**Comment by sdroege** [comment]
Looks good to me if that also works. I'll update my PR after this is merged to only include https://github.com/gtk-rs/gio/pull/139/commits/83e979cbb9a6976e41dc193298f85c467dfc91f3

**Comment by sdroege** [comment]
> If you could add a check for this on travis, it'd be awesome!

That's not too trivial, can we do that in a separate PR?

**Comment by sdroege** [comment]
Updated my PR to only have that one commit

**Comment by sdroege** [comment]
@meldron please add

```Fixes https://github.com/gtk-rs/gio/issues/137```

to the commit message at the bottom in a new line

**Comment by sdroege** [comment]
> @meldron I discussed about it with @sdroege and it's gonna be tricky (a qemu instance very certainly...). So just forget about it for now.

You can also cross-compile if you somehow get all the libraries needed (GTK, etc) for arm. Not sure if the ancient Ubuntu on travis already had proper multiarch support, in newer Ubuntu/Debian you can easily install those packages for other architectures.

And then you will probably have to fight with pkg-config. In any case, something for another PR.

**Comment by meldron** [comment]
Okay,

thanks for your help guys.

**Comment by sdroege** [comment]
> thanks for your help guys.

No problem, let me know if you run into other problems with the GStreamer bindings on ARM!

**Comment by sdroege** [comment]
All green

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
