### PR TITLE
Move trampolines

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of gtk-rs/gir#792

### CODE REVIEW

**Comment by sdroege** [comment]
Will you also do GLib? In object.rs there should be at least one, for the notify signal.

**Comment by GuillaumeGomez** [comment]
When I generated, nothing changed?

**Comment by sdroege** [comment]
There's manual code :)

**Comment by GuillaumeGomez** [comment]
Oh you meant updating the manual code! In case a function is used in different places, what should we do? Copy it or keep it "outside"?

**Comment by sdroege** [comment]
Not copy :) Keep it then

**Pull request merged**
