### PR TITLE
Fix/extend DataInputStream code

### PR DESCRIPTION
**Pull request by sdroege**
See individual commits.

### CODE REVIEW

**Comment by sdroege** [comment]
CC @EPashkin @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Sorry, I already looked at it but I can't provide a full review and be sure it's working. :-/ Do you have some precise points you want to highlight so I can agree that they are working as expected?

**Comment by EPashkin** [comment]
@sdroege Thanks, LGFM
Can you add `manual_traits = ["DataInputStreamExtManual"]` to Gir.toml too?

**Comment by GuillaumeGomez** [comment]
@EPashkin Great catch! We should definitely add a check to be sure we don't forget it.

I'll open an issue about it.

**Comment by sdroege** [comment]
>  Can you add `manual_traits = ["DataInputStreamExtManual"]` to Gir.toml too?

Done. Thanks for the reviews, I'll merge then after the CI is happy again :)

**Pull request merged**
