### PR TITLE
New release

### LINKED ISSUE #165: Compilation errors
```
error[E0277]: the trait bound `std::string::String: glib::translate::ToGlibPtr<'_, *mut i8>` is not satisfied
  --> /home/chessnokov/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.5.0/src/subprocess.rs:40:35
   |
40 |         let stdin_buf = stdin_buf.to_glib_full();
   |                                   ^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut i8>` is not implemented for `std::string::String`
   |
   = help: the following implementations were found:
             <std::string::String as glib::translate::ToGlibPtr<'a, *const u8>>
             <std::string::String as glib::translate::ToGlibPtr<'a, *mut u8>>
   = note: required because of the requirements on the impl of `glib::translate::ToGlibPtr<'_, *mut i8>` for `std::option::Option<std::string::String>`

error[E0308]: mismatched types
  --> /home/chessnokov/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.5.0/src/subprocess.rs:57:77
   |
57 |             ffi::g_subprocess_communicate_utf8_async(self.to_glib_none().0, stdin_buf, cancellable.0, Some(callback), Box::into_raw(user_data) as *mut _);
   |                                                                             ^^^^^^^^^ expected u8, found i8
   |
   = note: expected type `*const u8`
              found type `*mut i8`

error: aborting due to 2 previous errors

Some errors occurred: E0277, E0308.
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #165.

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
This breaks API. Only include that single fix please :)

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Thanks to both of you!

**Pull request merged**
