### PR TITLE
Add GSettingsSchemaSource bindings

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/gtk-rs/gio/issues/120

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me.

**Comment by EPashkin** [comment]
@sdroege Thanks, but there changes in src/auto/versions.txt but no submodule update.

**Comment by sdroege** [comment]
Done, removed the version.txt changes

**Comment by sdroege** [comment]
@GuillaumeGomez should be good to go then :) Was green on CI before I removed the version.txt change

**Comment by EPashkin** [comment]
Not fully green, but we can do nothing with futures-core :(

**Comment by sdroege** [comment]
Right, see https://github.com/rust-lang-nursery/futures-rs/issues/1031. Not much we can do about that other than removing the futures-nightly build from CI for now

**Comment by GuillaumeGomez** [comment]
Then I merge. Thanks!

**Pull request merged**
