### PR TITLE
Define manual traits

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/683

WIP as I added parent manual traits only up to file_input_stream.rs and trying teach gir do it.

### CODE REVIEW

**Comment by EPashkin** [comment]
Rebased

**Comment by EPashkin** [comment]
This seems ready too

**Comment by sdroege** [comment]
Looks good to me, will merge once it's done.

We'll also need this for `glib`, or not? `ObjectExt` is a manual trait there

**Comment by sdroege** [comment]
All good apart from the known failures, so let's get this in!

**Comment by EPashkin** [comment]
ObjectExt has same name as generated trait.
@GuillaumeGomez I just found that glib don't include lgpl docs.

**Comment by GuillaumeGomez** [comment]
Really? I'm a bit surprised...

**Pull request merged**
