### PR TITLE
0.9.1 release

### PR DESCRIPTION
**Pull request by sdroege**
CC @EPashkin @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
Not sure why this fails like that, but maybe we should add `// rustdoc-stripper-ignore-next` here? That's what it's supposed to be used for, right? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Indeed but it's supposed to put this documentation back. It's weird...

**Comment by sdroege** [comment]
> Indeed but it's supposed to put this documentation back. It's weird...

From where would it put it back? Is it in `lgpl-docs` `vendor.md`? If so we need to update that for this bugfix release, or just remove the docs, or rustdoc-stripper-ignore-next

**Comment by GuillaumeGomez** [comment]
Let's use `rustdoc-stripper-ignore-next` for now.

**Comment by sdroege** [comment]
Ok, seems this works :)

**Pull request merged**
