### PR TITLE
Mark functions to create a socket from raw fd/socket as unsafe

### PR DESCRIPTION
**Pull request by sdroege**
It's unsafe as one could pass any possible number as fd/handle here from
safe code otherwise.

### CODE REVIEW

**Comment by EPashkin** [comment]
Good catch, thanks,
There still needed some work for `impl AsXX for Socket` generate doc for different system.

**Comment by sdroege** [comment]
What work do you mean?

**Comment by EPashkin** [comment]
Both CI failed on cargo doc --features "dox"

**Comment by sdroege** [comment]
Ah didn't see that, I'm on the phone right now and the github mobile ui is quite useless for showing such things :)

Will fix later

**Comment by sdroege** [comment]
Finally! All green @GuillaumeGomez :)

**Comment by philn** [comment]
Was it green? `cargo build --features=futures,dox` fails here:

```
                                                                                                                                                                                                                  
error[E0605]: non-primitive cast: `i32` as `socket::RawSocket`                                                                                                                                                     
  --> src/socket.rs:64:13                                                                                                                                                                                          
   |                                                                                                                                                                                                               
64 |             ffi::g_socket_get_fd(self.to_glib_none().0) as _                                                                                                                                                  
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                  
   |                                                                                                                                                                                                               
   = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait       
```

**Comment by sdroege** [comment]
Apparently it was, yes. But I can reproduce that.

**Pull request merged**
