### PR TITLE
Dox

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Even though the regen is a bit useless. Should I remove it?

**Comment by EPashkin** [comment]
Yes, seems only needed "Add doc feature"

**Comment by GuillaumeGomez** [comment]
Only kept the last commit.

**Comment by EPashkin** [comment]
Strange that gio features don't depends for glib's.
IMHO `dox` need depends of `glib/dox`

**Comment by GuillaumeGomez** [comment]
Why that? If I follow your logic, `gtk` should add it for all its `gtk-rs`'s dependencies. Did I understood correctly?

**Comment by EPashkin** [comment]
`gtk` can add only `gdk/v_11` only because `gdk` add features for its dependencies.
`gio` has only one non-sys dependency `glib` but not limit it,
so if any program use only `gio` with limited version, it may not get right version of `glib`'s functions.

Same if someone try to build docs only for `gio` he get all functions for it but only part for `glib`.

**Comment by GuillaumeGomez** [comment]
Hum ok. Makes sense.

**Comment by EPashkin** [comment]
As it very rare case I ignore version limits for glib as it will be added by other crates,
For `dox` I also don't insist but IMHO better add it.

**Comment by GuillaumeGomez** [comment]
@EPashkin: Does it seem ok to you now?

**Comment by EPashkin** [comment]
@GuillaumeGomez  Yes, thanks

**Pull request merged**
