### PR TITLE
Add Gio.Notification bindings

### LINKED ISSUE #36: Missing functions for Notification
I'm trying to use the new notification API from Gtk3 (https://developer.gnome.org/gio/stable/GNotification.html), but there doesn't seem to be a binding in gio

### PR DESCRIPTION
**Pull request by nielsdg**
Should also fix #36

### CODE REVIEW

**Comment by EPashkin** [comment]
This not enough, you need do generate files in auto with `make gir` or it equivalent.
Also maybe gir just don't generate Notification due some errors.

**Comment by nielsdg** [comment]
Sorry 'bout that, should be fixed now :)

**Comment by EPashkin** [comment]
Please add NotificationPriority to generate and squash changes to one commit

**Comment by nielsdg** [comment]
Fixed!

**Comment by EPashkin** [comment]
Not fully, seems "Merge" is empty commit and need be removed.

**Comment by EPashkin** [comment]
@nielsdg, sorry, don't see that you merged FileInfo generation (normally it done with rebase). Thanks.

@GuillaumeGomez, 👍 for merge

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
