### PR TITLE
bind IOErrorEnum

### PR DESCRIPTION
**Pull request by ystreet**

### CODE REVIEW

**Comment by sdroege** [comment]
Are some variants of the enum only available on some platforms? I can't remember

Otherwise looks good to me

**Comment by GuillaumeGomez** [comment]
Strange travis error. I restarted the build.

**Comment by ystreet** [comment]
@sdroege There's no `#if` guards around any of the values in the gio C headers so I think the values are available everywhere however they may not exactly be used everywhere but that's not our problem :)

**Comment by EPashkin** [comment]
LGFM

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
