### PR TITLE
Make stub traits under feature="dox" public to include in doc

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gio/pull/80

cc @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
Reason that trait doc not generated because it was not public 😉 
@GuillaumeGomez can you check doc on linux? Seems text in `lgpl-docs` need some fixes: currently it shows as one line.
```html
<div class='docblock'><p>This is stub for doc generation
<a href="https://doc.rust-lang.org/std/os/unix/io/trait.IntoRawFd.html">Actual docs</a></p>
</div>
```

**Comment by GuillaumeGomez** [comment]
I can't find this sentence anywhere in the generated docs with a `grep`...

**Comment by EPashkin** [comment]
You looked for `This is stub for doc generation`?
Link pages in `target\doc\gio\socket` directory, actual pages in `target\doc\gio\prelude` but there too many pages.

**Comment by EPashkin** [comment]
@GuillaumeGomez I just remind you about this PR

**Comment by GuillaumeGomez** [comment]
Woups sorry!

**Comment by EPashkin** [comment]
@GuillaumeGomez Is [sample HMTL code](https://github.com/gtk-rs/gio/pull/81#issuecomment-364517056) was good for you?

**Comment by GuillaumeGomez** [comment]
Ah sorry, forgot to comment. Yes it was. At least didn't see any issue.

**Comment by EPashkin** [comment]
Thanks for review

**Pull request merged**
