### PR TITLE
Port to futures 0.3

### PR DESCRIPTION
**Pull request by sdroege**
While this requires nightly, the API is now stabilized and will become part of Rust 1.36. IMHO we should merge this now so that it can all get wider testing.

### CODE REVIEW

**Comment by sdroege** [comment]
This is currently marked as WIP because it uses https://github.com/gtk-rs/glib/pull/476 and https://github.com/gtk-rs/gir/pull/753 via Cargo patching

**Comment by sdroege** [comment]
I'll also change this to actually run the futures tests on nightly. And send another PR for that for glib.

Otherwise please review this one already but not merge yet.

**Comment by sdroege** [comment]
> I'll also change this to actually run the futures tests on nightly. And send another PR for that for glib.

Added and done

**Comment by EPashkin** [comment]
@sdroege Thanks. 👍.
Sourceview's `auto/search_context.rs` also affected by gir changes

**Comment by sdroege** [comment]
So let's get this in and then I do the examples first (they don't need the other crates updated), and then I do gdk-pixbuf, gtk and sourceview.

**Pull request merged**
