### PR TITLE
Various Source related cleanups and add PollableInputStream/PollableOutputStream

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Build failure is because of https://github.com/gtk-rs/glib/pull/312

**Comment by GuillaumeGomez** [comment]
Restarting ci.

**Comment by sdroege** [comment]
First that other PR has to be fixed :)

**Comment by EPashkin** [comment]
@sdroege Can you fix https://github.com/gtk-rs/gio/blob/master/src/test_util.rs too?

**Comment by sdroege** [comment]
@EPashkin Fix how? https://github.com/gtk-rs/gio/pull/107 ?

**Comment by EPashkin** [comment]
Yes, I was don't done reading all mails 😉

**Comment by EPashkin** [comment]
@GuillaumeGomez Sorry, but can you restart CI here too, it part of #108 and has more chance to pass CI

**Comment by sdroege** [comment]
yes this one should go in asap :)

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by EPashkin** [comment]
@GuillaumeGomez it only same rawfd error on travis, IMHO ready for merge.

**Comment by GuillaumeGomez** [comment]
I really need to fix glib...

**Pull request merged**
