### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/797

Followup #224 

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
CI passed

**Comment by EPashkin** [comment]
Ping

**Comment by GuillaumeGomez** [comment]
Ping @sdroege to be exact. :)

**Pull request merged**
