### PR TITLE
IsA<Cancellable> generic instead of concrete Option<&Cancellable>

### LINKED ISSUE #234: Manual bindings for functions with Cancellable args are inconsistent
For functions which take a `Cancellable`, auto-generated code looks like this:

```rust
fn foo<P: IsA<Cancellable>>(cancellable: Option<&P>) { ... }
```

But in some places in the manually-written bindings, there is this instead:

```rust
fn bar(cancellable: Option<&Cancellable>) { ... }
```

The following are the inconsistent ones I could find in gio:

```
PollableOutputStreamExtManual
  create_source
  create_source_future
  create_source_stream

InputStreamExtManual
  read
  read_all
  read_all_async
  read_async
  
Subprocess
  communicate_utf8_async
  

impl<F, O, T: 'static, E: 'static> GioFuture<F, O, T, E>
where
    O: Clone + 'static,
    F: FnOnce(&O, oneshot::Sender<Result<T, E>>) -> Cancellable + 'static,
    not sure if it makes sense to let the operation return an IsA<Cancellable> here

    same for impl<F, O, T, E> Future for GioFuture<F, O, T, E>

SocketListenerExtManual
  accept_socket_async
  
SocketExtManual
  receive
  receive_from
  receive_with_blocking
  send
  send_to
  send_with_blocking
  create_source
  create_source_future
  create_source_stream

PollableInputStreamExtManual
  create_source
  create_source_future
  create_source_stream
  read_nonblocking
  
OutputStreamExtManual
  write_async
  write_all
  write_all_async
  
FileExtManual
  replace_contents_async
```

### PR DESCRIPTION
**Pull request by federicomenaquintero**
Fixes #234

### CODE REVIEW

**Comment by federicomenaquintero** [comment]
I just need to know if I should do the same on the relatively new subclass/*stream.rs :)

**Comment by EPashkin** [comment]
IMHO `InputStreamImplExt` etc. don't need `IsA<Cancelable>` to minimize code size

**Comment by sdroege** [comment]
> I just need to know if I should do the same on the relatively new subclass/*stream.rs :)

See https://github.com/gtk-rs/gio/issues/234#issuecomment-534439952. Short answer is "no" :)

**Comment by sdroege** [comment]
@federicomenaquintero the build is failing in all configurations it seems :)

**Comment by federicomenaquintero** [comment]
Sorry, I forgot the tests!  Fixed now.

**Comment by sdroege** [comment]
> Sorry, I forgot the tests! Fixed now.

Some more are fixed now, but I think you forgot at least the futures code :) See https://travis-ci.org/gtk-rs/gio/jobs/589194656

Try running tests with `--features=v2_60,futures`

**Comment by federicomenaquintero** [comment]
Uuuh... is that a cargo bug in the MacOS builds?

**Comment by sdroege** [comment]
> Uuuh... is that a cargo bug in the MacOS builds?

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/tools/cargo/src/cargo/util/cpu.rs:152:29

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Is clearly a bug in cargo, yes. Feel like reporting it? :D

**Comment by federicomenaquintero** [comment]
Thanks!  I'll try a run in my private repo with RUST_BACKTRACE=1 in the Travis environment to see if that gets useful info out of cargo panicking...

**Pull request merged**
